version: '3.8'
services:
  simple1:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - .:/app